/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JList;
import pc.PCChen;
import pc.Pokemon;

/**
 *
 * @author thouverez
 */
public class MainFrame extends javax.swing.JFrame {

    private PCChen pc;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() throws SQLException {
        this.pc = new PCChen();
        initComponents();
        initFrame();
        setTitle("PC de Chen");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dresseurField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnConnect = new javax.swing.JButton();
        errorPanel = new javax.swing.JLabel();
        panelPoche = new javax.swing.JPanel();
        lPoche = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPokDetenus = new javax.swing.JList<>();
        panelSelectionne = new javax.swing.JPanel();
        labelNomPok = new javax.swing.JLabel();
        panelInfo = new javax.swing.JPanel();
        lNiveau = new javax.swing.JLabel();
        lStockage = new javax.swing.JLabel();
        labelNiveau = new javax.swing.JLabel();
        labelStockage = new javax.swing.JLabel();
        transVersPoche = new javax.swing.JButton();
        transVersPC = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        panelBoites = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPokStockes = new javax.swing.JList<>();
        cbBoiteTrans = new javax.swing.JComboBox<>();
        lBoite = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        dresseurField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dresseurFieldKeyPressed(evt);
            }
        });

        jLabel2.setText("Dresseur, quel est ton nom ?");

        btnConnect.setText("Valider");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        lPoche.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lPoche.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lPoche.setText("Pokémons dans ta poche");

        listPokDetenus.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listPokDetenusValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listPokDetenus);

        javax.swing.GroupLayout panelPocheLayout = new javax.swing.GroupLayout(panelPoche);
        panelPoche.setLayout(panelPocheLayout);
        panelPocheLayout.setHorizontalGroup(
            panelPocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lPoche, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        panelPocheLayout.setVerticalGroup(
            panelPocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPocheLayout.createSequentialGroup()
                .addComponent(lPoche)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        labelNomPok.setFont(new java.awt.Font("Ink Free", 1, 36)); // NOI18N
        labelNomPok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNomPok.setText("Nom_pok");

        lNiveau.setText("Niveau : ");

        lStockage.setText("Stockage :");

        labelNiveau.setText("niveau");

        labelStockage.setText("lieu_stockage");

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNiveau, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lStockage, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNiveau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelStockage, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNiveau, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNiveau, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStockage, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lStockage, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addContainerGap())
        );

        transVersPoche.setText("Transférer dans la poche");
        transVersPoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transVersPocheActionPerformed(evt);
            }
        });

        transVersPC.setText("Transférer au PC");
        transVersPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transVersPCActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Pokémon sélectionné");

        javax.swing.GroupLayout panelSelectionneLayout = new javax.swing.GroupLayout(panelSelectionne);
        panelSelectionne.setLayout(panelSelectionneLayout);
        panelSelectionneLayout.setHorizontalGroup(
            panelSelectionneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSelectionneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSelectionneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(transVersPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transVersPoche, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelNomPok, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSelectionneLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(73, 73, 73))
            .addGroup(panelSelectionneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelSelectionneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelSelectionneLayout.setVerticalGroup(
            panelSelectionneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSelectionneLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNomPok, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(transVersPoche, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transVersPC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelSelectionneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelSelectionneLayout.createSequentialGroup()
                    .addGap(120, 120, 120)
                    .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(112, Short.MAX_VALUE)))
        );

        listPokStockes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listPokStockesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listPokStockes);

        cbBoiteTrans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        cbBoiteTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBoiteTransActionPerformed(evt);
            }
        });

        lBoite.setText("Boite :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Pokémons sur le PC");

        javax.swing.GroupLayout panelBoitesLayout = new javax.swing.GroupLayout(panelBoites);
        panelBoites.setLayout(panelBoitesLayout);
        panelBoitesLayout.setHorizontalGroup(
            panelBoitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBoitesLayout.createSequentialGroup()
                .addGroup(panelBoitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBoitesLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lBoite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbBoiteTrans, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBoitesLayout.setVerticalGroup(
            panelBoitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBoitesLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelBoitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbBoiteTrans, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBoitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lBoite)))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelPoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelSelectionne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelBoites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(dresseurField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConnect)
                        .addGap(18, 18, 18)
                        .addComponent(errorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnConnect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dresseurField)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(errorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelSelectionne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPoche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBoites, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        verifConnection();
    }//GEN-LAST:event_btnConnectActionPerformed

    private void dresseurFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dresseurFieldKeyPressed
        if (evt.getKeyCode() == 10) {
            verifConnection();
        }
    }//GEN-LAST:event_dresseurFieldKeyPressed

    private void transVersPocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transVersPocheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transVersPocheActionPerformed

    private void transVersPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transVersPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transVersPCActionPerformed

    private void cbBoiteTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBoiteTransActionPerformed
        try {
            clearSelectedPanel();
            setupFrame();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbBoiteTransActionPerformed

    private void listPokDetenusValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listPokDetenusValueChanged
        if (!evt.getValueIsAdjusting()) {//This line prevents double events
            int ind = listPokDetenus.getSelectedIndex();

            if (ind >= 0) {
                Pokemon pok = new Pokemon();
                try {
                    pok = this.pc.getPokemonDetenus().get(ind);
                } catch (SQLException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    setupSelectPanel(pok, "poche");
                } catch (SQLException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_listPokDetenusValueChanged

    private void listPokStockesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listPokStockesValueChanged
        if (!evt.getValueIsAdjusting()) {//This line prevents double events
            int boite = Integer.parseInt(cbBoiteTrans.getSelectedItem().toString()) - 1;
            int ind = listPokStockes.getSelectedIndex();

            if (ind >= 0) {
                Pokemon pok = new Pokemon();
                try {
                    pok = this.pc.getPokemonBoite(boite).get(ind);
                } catch (SQLException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    setupSelectPanel(pok, "PC boite " + (boite + 1));
                } catch (SQLException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_listPokStockesValueChanged

    public void verifConnection() {
        errorPanel.setText("");
        String nDress = dresseurField.getText();
        if ("".equals(nDress)) {
            errorPanel.setText("Tu dois écrire quelquechose!");
        } else {
            try {
                boolean con = this.pc.connecteDresseur(nDress);
                initFrame();
                if (con) {
                    errorPanel.setText("Connecté en tant que " + nDress);
                    setupFrame();
                } else {
                    errorPanel.setText("Dresseur " + nDress + " inconnu");
                }
                System.out.println("Connu " + con);
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void setupSelectPanel(Pokemon p, String stockage) throws SQLException {
        clearSelectedPanel();
        this.labelNomPok.setText(p.getNom());
        this.labelNiveau.setText("" + p.getLvl());
        this.labelStockage.setText(stockage);
        if (stockage.equals("poche")) {
            int boite = Integer.parseInt(cbBoiteTrans.getSelectedItem().toString());
            transVersPC.setText("Transférer vers la boite " + boite);
            transVersPC.setVisible(true);
        } else {
            transVersPoche.setVisible(true);
        }
    }

    public void clearSelectedPanel() throws SQLException {
        this.transVersPoche.setVisible(false);
        this.transVersPC.setVisible(false);
        this.labelNomPok.setText("");
        this.labelNiveau.setText("");
        this.labelStockage.setText("");

    }

    public void setupFrame() throws SQLException {
        DefaultListModel<String> strList = new DefaultListModel<>();
        for (Pokemon p : this.pc.getPokemonDetenus()) {
            strList.addElement(p.toString());
        }
        this.listPokDetenus.setModel(strList);
        int boite = Integer.parseInt(cbBoiteTrans.getSelectedItem().toString()) - 1;
        strList = new DefaultListModel<>();
        for (Pokemon p : this.pc.getPokemonBoite(boite)) {
            strList.addElement(p.toString());
        }
        this.listPokStockes.setModel(strList);
        cbBoiteTrans.setEnabled(true);

    }

    public void initFrame() {
        this.listPokDetenus.setModel(new DefaultListModel<>());
        this.listPokStockes.setModel(new DefaultListModel<>());
        errorPanel.setText("");
        labelNomPok.setText("");
        labelNiveau.setText("");
        labelStockage.setText("");
        transVersPC.setVisible(false);
        transVersPoche.setVisible(false);
        cbBoiteTrans.setVisible(true);
        cbBoiteTrans.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JComboBox<String> cbBoiteTrans;
    private javax.swing.JTextField dresseurField;
    private javax.swing.JLabel errorPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lBoite;
    private javax.swing.JLabel lNiveau;
    private javax.swing.JLabel lPoche;
    private javax.swing.JLabel lStockage;
    private javax.swing.JLabel labelNiveau;
    private javax.swing.JLabel labelNomPok;
    private javax.swing.JLabel labelStockage;
    private javax.swing.JList<String> listPokDetenus;
    private javax.swing.JList<String> listPokStockes;
    private javax.swing.JPanel panelBoites;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelPoche;
    private javax.swing.JPanel panelSelectionne;
    private javax.swing.JButton transVersPC;
    private javax.swing.JButton transVersPoche;
    // End of variables declaration//GEN-END:variables
}
