/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import pc.PCChen;
import pc.Pokemon;

/**
 *
 * @author thouverez
 */
public class MainFrame extends javax.swing.JFrame {

    private PCChen pc;
    private Pokemon selectedPok;
    private int selectedIndex;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() throws SQLException {
        this.pc = new PCChen();
        initComponents();
        initFrame();
        setTitle("PC de Chen");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dresseurField = new javax.swing.JTextField();
        lNom = new javax.swing.JLabel();
        btnConnect = new javax.swing.JButton();
        errorPanel = new javax.swing.JLabel();
        panelPoche = new javax.swing.JPanel();
        lPoche = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPokDetenus = new javax.swing.JList<>();
        panelSelectionne = new javax.swing.JPanel();
        labelNomPok = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lNiveau = new javax.swing.JLabel();
        lStockage = new javax.swing.JLabel();
        labelNiveau = new javax.swing.JLabel();
        labelStockage = new javax.swing.JLabel();
        transVersPoche = new javax.swing.JButton();
        transVersPC = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPokStockes = new javax.swing.JList<>();
        lPoche2 = new javax.swing.JLabel();
        cbBoiteTrans = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        dresseurField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dresseurFieldKeyPressed(evt);
            }
        });

        lNom.setText("Dresseur, quel est ton nom ?");

        btnConnect.setText("Valider");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        lPoche.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lPoche.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lPoche.setText("Pokémons dans ta poche");

        listPokDetenus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listPokDetenus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listPokDetenusMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listPokDetenus);

        javax.swing.GroupLayout panelPocheLayout = new javax.swing.GroupLayout(panelPoche);
        panelPoche.setLayout(panelPocheLayout);
        panelPocheLayout.setHorizontalGroup(
            panelPocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPocheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panelPocheLayout.createSequentialGroup()
                        .addComponent(lPoche, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPocheLayout.setVerticalGroup(
            panelPocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPocheLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lPoche)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        labelNomPok.setFont(new java.awt.Font("Ink Free", 1, 36)); // NOI18N
        labelNomPok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lNiveau.setText("Niveau : ");

        lStockage.setText("Stockage :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lStockage, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(lNiveau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelNiveau, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(labelStockage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelNiveau, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNiveau, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lStockage, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStockage, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        transVersPoche.setText("→ Poche");
        transVersPoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transVersPocheActionPerformed(evt);
            }
        });

        transVersPC.setText("→ PC");
        transVersPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transVersPCActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Pokémon sélectionné");

        javax.swing.GroupLayout panelSelectionneLayout = new javax.swing.GroupLayout(panelSelectionne);
        panelSelectionne.setLayout(panelSelectionneLayout);
        panelSelectionneLayout.setHorizontalGroup(
            panelSelectionneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSelectionneLayout.createSequentialGroup()
                .addGroup(panelSelectionneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSelectionneLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelSelectionneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelNomPok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)))
                    .addGroup(panelSelectionneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(transVersPoche, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transVersPC, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelSelectionneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelSelectionneLayout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelSelectionneLayout.setVerticalGroup(
            panelSelectionneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSelectionneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(labelNomPok, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(panelSelectionneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transVersPoche, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transVersPC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
            .addGroup(panelSelectionneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelSelectionneLayout.createSequentialGroup()
                    .addGap(92, 92, 92)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(92, Short.MAX_VALUE)))
        );

        listPokStockes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listPokStockes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listPokStockesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listPokStockes);

        lPoche2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lPoche2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lPoche2.setText("PC - Boite ");

        cbBoiteTrans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        cbBoiteTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBoiteTransActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(cbBoiteTrans, 0, 73, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lPoche2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(cbBoiteTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lPoche2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSelectionne, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lNom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dresseurField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConnect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(dresseurField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lNom, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnConnect))
                    .addComponent(errorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelPoche, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSelectionne, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        verifConnection();
    }//GEN-LAST:event_btnConnectActionPerformed

    private void dresseurFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dresseurFieldKeyPressed
        if (evt.getKeyCode() == 10) {
            verifConnection();
        }
    }//GEN-LAST:event_dresseurFieldKeyPressed

    private void transVersPocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transVersPocheActionPerformed
        
    }//GEN-LAST:event_transVersPocheActionPerformed

    private void transVersPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transVersPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transVersPCActionPerformed

    private void listPokDetenusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPokDetenusMouseClicked
        this.selectedIndex = listPokDetenus.getSelectedIndex();

        if (this.selectedIndex >= 0) {
            try {
                this.selectedPok = this.pc.getPokemonDetenus().get(this.selectedIndex);
                setupSelectPanel("Poche");
            } catch (SQLException | IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_listPokDetenusMouseClicked

    
    
    private void cbBoiteTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBoiteTransActionPerformed

    }//GEN-LAST:event_cbBoiteTransActionPerformed

    
    
    private void listPokStockesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPokStockesMouseClicked

    }//GEN-LAST:event_listPokStockesMouseClicked

    public void verifConnection() {
        errorPanel.setText("");
        String nDress = dresseurField.getText();
        if ("".equals(nDress)) {
            errorPanel.setText("Tu dois écrire quelquechose!");
        } else {
            try {
                boolean con = this.pc.connecteDresseur(nDress);
                initFrame();
                if (con) {
                    errorPanel.setText("Connecté en tant que " + nDress);
                    setupFrame();
                } else {
                    errorPanel.setText("Dresseur " + nDress + " inconnu");
                }
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }

    public void setupSelectPanel(String stockage) throws MalformedURLException, IOException {
        //String path = "https://i1.wp.com/www.poketips.fr/wp-content/uploads/2016/07/"+String.format("%03d", p.getId())+".png?w=750";
        //System.out.println("Get Image from " + path);
        //URL url = new URL(path);
        //BufferedImage image = ImageIO.read(url.openStream());
        //System.out.println("Load image into frame...");
        //this.lPicture = new JLabel(new ImageIcon(image));
        this.labelNomPok.setText(selectedPok.getNom());
        this.labelNiveau.setText("" + selectedPok.getLvl());
        this.labelStockage.setText(stockage);
        lNiveau.setVisible(true);
        lStockage.setVisible(true);
        labelNiveau.setVisible(true);
        labelStockage.setVisible(true);
        transVersPC.setVisible(true);
        
        if(stockage.charAt(0) == 'P') {
            transVersPC.setEnabled(true);
            transVersPoche.setEnabled(false);
        } else {
            transVersPC.setEnabled(false);
            transVersPoche.setEnabled(true);
        }
    }

    public void setupFrame() throws SQLException {
        DefaultListModel<String> strList = new DefaultListModel<>();
        for (Pokemon p : this.pc.getPokemonDetenus()) {
            strList.addElement(p.toString());
        }
        this.listPokDetenus.setModel(strList);
        //ArrayList<Pokemon> pokemonBoite = this.pc.getPokemonBoite(Integer.parseInt(this.cbBoiteTrans.getSelectedItem().toString()));
        //strList = new DefaultListModel<>();
        //for (Pokemon p : pokemonBoite) {
        //    strList.addElement(p.toString());
        //}
       // this.listPokStockes.setModel(strList);
        listPokDetenus.setEnabled(true);
        //listPokStockes.setEnabled(true);
        this.cbBoiteTrans.setEnabled(true);

    }

    public void initFrame() {

        listPokDetenus.setModel(new DefaultListModel<>());
        listPokStockes.setModel(new DefaultListModel<>());
        listPokDetenus.setEnabled(false);
        listPokStockes.setEnabled(false);

        errorPanel.setText("");
        lNiveau.setVisible(false);
        lStockage.setVisible(false);
        labelNomPok.setText("");
        labelNiveau.setText("");
        labelStockage.setText("");
        transVersPC.setEnabled(false);
        transVersPoche.setEnabled(false);
        this.cbBoiteTrans.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JComboBox<String> cbBoiteTrans;
    private javax.swing.JTextField dresseurField;
    private javax.swing.JLabel errorPanel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lNiveau;
    private javax.swing.JLabel lNom;
    private javax.swing.JLabel lPoche;
    private javax.swing.JLabel lPoche2;
    private javax.swing.JLabel lStockage;
    private javax.swing.JLabel labelNiveau;
    private javax.swing.JLabel labelNomPok;
    private javax.swing.JLabel labelStockage;
    private javax.swing.JList<String> listPokDetenus;
    private javax.swing.JList<String> listPokStockes;
    private javax.swing.JPanel panelPoche;
    private javax.swing.JPanel panelSelectionne;
    private javax.swing.JButton transVersPC;
    private javax.swing.JButton transVersPoche;
    // End of variables declaration//GEN-END:variables

}
